compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@openzeppelin=/Users/chriswong/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.6.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
dev_deployment_artifacts: true
dotenv: .env