compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@openzeppelin=/Users/chriswong/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.6.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
dotenv: .env
dev_deployment_artifacts: false
console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs
networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null